import { CATEGORY_ORDER, type Product, type Category, type Sport } from "./types";

/**
 * Sample catalogue. Prices in CENTS.
 *
 * Swap this array for a CMS/commerce fetch — every consumer goes through
 * the helpers at the bottom, so the change is local to this file.
 */
export const PRODUCTS: Product[] = [
  /* ---------------- Grails ---------------- */
  {
    slug: "1986-fleer-jordan-rookie-psa-10",
    brand: "Other",
    condition: "graded",
    sku: "ARN-C-0001",
    category: "card",
    name: "1986 Fleer #57",
    subject: "Michael Jordan",
    year: 1986,
    sport: "Basketball",
    price: 48000000,
    stock: 1,
    tagline: "The cornerstone rookie of the entire hobby.",
    accent: "#FF5A1F",
    featured: true,
    hot: true,
    story: [
      "No card carries the weight of the '86 Fleer Jordan. It is the axis the modern hobby turns on — the card every other basketball rookie gets measured against.",
      "This one is exceptional even among exceptional copies. Razor corners on all four, centering around 55/45, and a surface free of the print snow that plagues the issue.",
      "Fewer than one in four hundred submissions hit this grade. Terminal example.",
    ],
    spec: {
      set: "1986–87 Fleer Basketball",
      cardNumber: "57",
      grader: "PSA",
      grade: "GEM MT 10",
      certNumber: "84119063",
      popAtGrade: 328,
      popHigher: 0,
      surface: "No print defects under 10× loupe",
    },
    provenance: [
      { year: "1986", title: "Pack pulled", detail: "Chicago metro; held by the original owner." },
      { year: "2004", title: "Graded", detail: "PSA GEM MT 10 on first submission." },
      { year: "2019", title: "Private treaty", detail: "Acquired from the original owner's estate." },
      { year: "2026", title: "Listed by ARENA", detail: "Re-examined and re-photographed in house." },
    ],
  },
  {
    slug: "1952-topps-mantle-sgc-6",
    brand: "Topps",
    condition: "graded",
    sku: "ARN-C-0002",
    category: "card",
    name: "1952 Topps #311",
    subject: "Mickey Mantle",
    year: 1952,
    sport: "Baseball",
    price: 125000000,
    stock: 1,
    tagline: "The card that made collecting a serious pursuit.",
    accent: "#2563EB",
    featured: true,
    story: [
      "Not a rookie card — something rarer. The '52 Topps Mantle is the card that turned a kids' pastime into a discipline, issued in the scarce high-number series that famously ended up in the Atlantic.",
      "This copy presents far better than the number suggests. Deep unfaded blue, clean portrait, minimal print lines, centering near 60/40. Honest even wear.",
    ],
    spec: {
      set: "1952 Topps Baseball",
      cardNumber: "311",
      grader: "SGC",
      grade: "EX-NM 6",
      certNumber: "10218847",
      popAtGrade: 74,
      popHigher: 112,
      surface: "Minimal print lines, strong original gloss",
    },
    provenance: [
      { year: "1952", title: "High-number series", detail: "Limited late-season regional distribution." },
      { year: "1991", title: "Public auction", detail: "East Coast sale; lot records retained." },
      { year: "2013", title: "Encapsulated", detail: "SGC EX-NM 6; holder untouched since." },
      { year: "2026", title: "Listed by ARENA", detail: "Full condition report completed." },
    ],
  },
  {
    slug: "2000-playoff-contenders-brady-rookie-ticket",
    brand: "Panini",
    condition: "graded",
    sku: "ARN-C-0003",
    category: "card",
    name: "2000 Playoff Contenders #144",
    subject: "Tom Brady",
    year: 2000,
    sport: "Football",
    price: 39500000,
    stock: 1,
    tagline: "The rookie ticket. Football's modern grail.",
    accent: "#1D4ED8",
    featured: true,
    hot: true,
    story: [
      "The single most important modern football card. On-card autograph, printed in a year when nobody knew what they had.",
      "Bold, complete signature with excellent placement and no bleed. Sharp corners, clean ticket edge, autograph graded 10.",
    ],
    spec: {
      set: "2000 Playoff Contenders Football",
      cardNumber: "144",
      grader: "PSA",
      grade: "NM-MT 8",
      certNumber: "91038442",
      popAtGrade: 61,
      popHigher: 38,
      surface: "On-card autograph, PSA 10 auto grade",
    },
    provenance: [
      { year: "2000", title: "Pack pulled", detail: "From a Contenders hobby box at release." },
      { year: "2010", title: "Graded", detail: "PSA NM-MT 8, autograph 10." },
      { year: "2026", title: "Listed by ARENA", detail: "Autograph checked against period exemplars." },
    ],
  },
  {
    slug: "1986-fleer-basketball-wax-box-bbce",
    brand: "Other",
    sku: "ARN-W-0001",
    category: "wax",
    name: "1986–87 Fleer Wax Box",
    subject: "Sealed Hobby Wax",
    year: 1986,
    sport: "Basketball",
    price: 62500000,
    stock: 1,
    tagline: "36 unopened packs. The Jordan is still in there.",
    accent: "#F59E0B",
    featured: true,
    hot: true,
    story: [
      "The closest the hobby gets to a lottery ticket with forty years of history behind it. Thirty-six packs, twelve cards each, and somewhere inside a shot at the rookie that defines the set.",
      "BBCE authenticated from a sealed case — the strongest provenance available for the issue. Outer cellophane original and unbroken, no resealing indicators under UV.",
    ],
    spec: {
      set: "1986–87 Fleer Basketball",
      format: "Wax Box",
      packCount: "36 packs × 12 cards",
      sealType: "Original factory cellophane",
      grader: "BBCE",
      grade: "From A Sealed Case",
      certNumber: "BBCE-3391047",
      sealIntegrity: "Unbroken; no resealing indicators under UV",
    },
    provenance: [
      { year: "1986", title: "Factory case", detail: "Part of a sealed twelve-box case." },
      { year: "2001", title: "Case broken", detail: "Boxes sold individually, unopened." },
      { year: "2015", title: "BBCE authenticated", detail: "Verified From A Sealed Case." },
      { year: "2026", title: "Listed by ARENA", detail: "Seal re-verified on intake." },
    ],
  },

  /* ---------------- Mid tier ---------------- */
  {
    slug: "1996-97-topps-chrome-kobe-rookie-psa-9",
    brand: "Topps",
    condition: "graded",
    sku: "ARN-C-0004",
    category: "card",
    name: "1996–97 Topps Chrome #138",
    subject: "Kobe Bryant",
    year: 1996,
    sport: "Basketball",
    price: 6200000,
    stock: 1,
    tagline: "The chrome rookie you build a Kobe collection around.",
    accent: "#7C3AED",
    story: [
      "Chrome's first year gave the hobby the Kobe rookie serious collectors anchor to. The stock scratches if you look at it wrong, which is why high grades stay scarce.",
      "Clean under angled light, sharp corners, strong centering.",
    ],
    spec: {
      set: "1996–97 Topps Chrome Basketball",
      cardNumber: "138",
      grader: "PSA",
      grade: "MINT 9",
      certNumber: "68240117",
      popAtGrade: 2140,
      popHigher: 231,
    },
    provenance: [
      { year: "1996", title: "Hobby release", detail: "Pulled at release." },
      { year: "2012", title: "Graded", detail: "PSA MINT 9." },
      { year: "2026", title: "Listed by ARENA", detail: "Surface verified, holder unmarked." },
    ],
  },
  {
    slug: "2003-04-topps-chrome-lebron-bgs-9-5",
    brand: "Topps",
    condition: "graded",
    sku: "ARN-C-0005",
    category: "card",
    name: "2003–04 Topps Chrome #111",
    subject: "LeBron James",
    year: 2003,
    sport: "Basketball",
    price: 5400000,
    compareAt: 6100000,
    stock: 1,
    tagline: "The defining chrome rookie of the modern era.",
    accent: "#8B5CF6",
    featured: true,
    story: [
      "The 2003 Chrome class is the bridge between the vintage hobby and the modern one, and the LeBron is its anchor.",
      "BGS 9.5 with 10s in centering and corners. Chrome clean under raking light — no scratching, no print haze.",
    ],
    spec: {
      set: "2003–04 Topps Chrome Basketball",
      cardNumber: "111",
      grader: "BGS",
      grade: "GEM MINT 9.5",
      certNumber: "0014882201",
      popAtGrade: 1892,
      popHigher: 143,
      surface: "Subs: 10 / 10 / 9.5 / 9.5",
    },
    provenance: [
      { year: "2003", title: "Release", detail: "Pulled from a hobby box." },
      { year: "2016", title: "Graded", detail: "BGS 9.5 Gem Mint." },
      { year: "2026", title: "Listed by ARENA", detail: "Re-examined under raking light." },
    ],
  },
  {
    slug: "1955-topps-clemente-rookie-psa-5",
    brand: "Topps",
    condition: "graded",
    sku: "ARN-C-0006",
    category: "card",
    name: "1955 Topps #164",
    subject: "Roberto Clemente",
    year: 1955,
    sport: "Baseball",
    price: 4400000,
    stock: 1,
    tagline: "Vintage colour that still carries a room.",
    accent: "#EA580C",
    story: [
      "Horizontal format, saturated colour, and a subject whose legacy runs well past the field.",
      "Outstanding colour for the grade with no fading in the red. Honest corner wear, no creases, clean reverse.",
    ],
    spec: {
      set: "1955 Topps Baseball",
      cardNumber: "164",
      grader: "PSA",
      grade: "EX 5",
      certNumber: "52901883",
      popAtGrade: 412,
      popHigher: 688,
    },
    provenance: [
      { year: "1955", title: "Original release", detail: "Topps 1955 series." },
      { year: "1998", title: "Graded", detail: "PSA EX 5." },
      { year: "2026", title: "Listed by ARENA", detail: "Colour and reverse verified." },
    ],
  },
  {
    slug: "1999-bowman-chrome-baseball-hobby-box",
    brand: "Topps",
    sku: "ARN-W-0002",
    category: "wax",
    name: "1999 Bowman Chrome Hobby Box",
    subject: "Sealed Hobby Wax",
    year: 1999,
    sport: "Baseball",
    price: 3800000,
    stock: 1,
    tagline: "A sealed window onto a stacked rookie class.",
    accent: "#059669",
    story: [
      "Breakers have steadily eaten the surviving population of sealed '99 Bowman Chrome. What's left shrinks every year.",
      "Factory shrink intact and tight, original seams visible along the short edges. No soft spots, no re-wrap sheen.",
    ],
    spec: {
      set: "1999 Bowman Chrome Baseball",
      format: "Hobby Box",
      packCount: "24 packs × 4 cards",
      sealType: "Factory shrink wrap",
      grader: "None",
      sealIntegrity: "Intact factory shrink, original seams verified",
    },
    provenance: [
      { year: "1999", title: "Hobby release", detail: "Direct from hobby distribution." },
      { year: "2026", title: "Listed by ARENA", detail: "Shrink inspected under raking light." },
    ],
  },
  {
    slug: "ali-signed-everlast-glove",
    sku: "ARN-S-0001",
    category: "signed",
    name: "Signed Everlast Glove",
    subject: "Muhammad Ali",
    year: 1996,
    sport: "Boxing",
    price: 2850000,
    stock: 1,
    tagline: "A clean, full signature from the most famous hand in sport.",
    accent: "#DC2626",
    featured: true,
    story: [
      "Red Everlast training glove signed across the palm in black marker. Complete and steady — signed in 1996, before the tremor shortened his autograph.",
      "Beckett authenticated with a full letter. Presented on a walnut base under museum-grade acrylic.",
    ],
    spec: {
      item: "Everlast training glove, right hand",
      inscription: "Signed across palm",
      medium: "Black marker on leather",
      authenticator: "Beckett",
      certNumber: "BAS-A81204",
      signingContext: "Private signing, 1996 — LOA on file",
      dimensions: "Cased 34 × 28 × 28 cm",
    },
    provenance: [
      { year: "1996", title: "Private signing", detail: "Documented signing session." },
      { year: "2009", title: "Authenticated", detail: "Beckett full LOA issued." },
      { year: "2026", title: "Listed by ARENA", detail: "Case renewed, signature re-photographed." },
    ],
  },
  {
    slug: "jack-nicklaus-signed-1986-masters-flag",
    sku: "ARN-S-0002",
    category: "signed",
    name: "1986 Masters Pin Flag",
    subject: "Jack Nicklaus",
    year: 1986,
    sport: "Golf",
    price: 1640000,
    stock: 1,
    tagline: "Signed and dated for the sixth green jacket.",
    accent: "#16A34A",
    story: [
      "Masters pin flag signed and dated by Nicklaus in reference to the 1986 win — the sixth, and the one nobody saw coming.",
      "Signature sits cleanly in the white field with strong ink flow and no feathering. JSA authenticated.",
    ],
    spec: {
      item: "Masters embroidered pin flag",
      inscription: "Signed and dated '86",
      medium: "Black marker on cotton",
      authenticator: "JSA",
      certNumber: "JSA-CC41180",
      signingContext: "Signed and dated in reference to the 1986 Masters",
      dimensions: "Framed 58 × 58 cm",
    },
    provenance: [
      { year: "1986", title: "Tournament year", detail: "Period Masters pin flag." },
      { year: "2014", title: "Signed", detail: "Signed and dated by Nicklaus." },
      { year: "2026", title: "Listed by ARENA", detail: "Conservation framed with UV glazing." },
    ],
  },
  {
    slug: "1979-80-opc-gretzky-rookie-psa-8",
    brand: "Other",
    condition: "graded",
    sku: "ARN-C-0007",
    category: "card",
    name: "1979–80 O-Pee-Chee #18",
    subject: "Wayne Gretzky",
    year: 1979,
    sport: "Hockey",
    price: 9600000,
    stock: 0,
    tagline: "Hockey's holy grail in a grade that still sings.",
    accent: "#0284C7",
    story: [
      "One of the most condition-sensitive cards ever printed. Rough cuts and chronic centering problems mean even well-kept copies rarely clear an 8.",
      "Strong corners for the grade, clean borders, none of the wax staining common to the issue.",
    ],
    spec: {
      set: "1979–80 O-Pee-Chee Hockey",
      cardNumber: "18",
      grader: "PSA",
      grade: "NM-MT 8",
      certNumber: "77410923",
      popAtGrade: 1043,
      popHigher: 271,
    },
    provenance: [
      { year: "1979", title: "Canadian release", detail: "O-Pee-Chee distribution, Ontario." },
      { year: "2008", title: "Graded", detail: "PSA NM-MT 8." },
      { year: "2026", title: "Sold by ARENA", detail: "Placed with a private collection." },
    ],
  },
  {
    slug: "maradona-1986-signed-shirt",
    sku: "ARN-S-0003",
    category: "signed",
    name: "1986 Argentina Shirt",
    subject: "Diego Maradona",
    year: 1986,
    sport: "Soccer",
    price: 4950000,
    stock: 0,
    tagline: "Signed by the hand that changed a tournament.",
    accent: "#0891B2",
    story: [
      "A 1986 Argentina home shirt in the classic Le Coq Sportif cut, signed across the front in silver paint pen. Bold, unhesitating, full-length — not the abbreviated scrawl of his later years.",
      "Signed in person in Buenos Aires with photographic documentation on file. PSA/DNA authenticated against period exemplars.",
    ],
    spec: {
      item: "Argentina home shirt, replica cut",
      inscription: "Signed in silver paint pen, front",
      medium: "Silver paint pen on polyester",
      authenticator: "PSA/DNA",
      certNumber: "AN0119284",
      signingContext: "Signed in person, Buenos Aires — photo-documented",
      dimensions: "Adult L; framed 92 × 74 cm",
    },
    provenance: [
      { year: "1986", title: "Shirt made", detail: "Period Le Coq Sportif shirt." },
      { year: "1998", title: "Signing", detail: "Signed in person, photographed." },
      { year: "2011", title: "Authenticated", detail: "PSA/DNA full authentication." },
      { year: "2026", title: "Sold by ARENA", detail: "Placed with a European collection." },
    ],
  },

  /* ---------------- Accessible / entry tier ---------------- */
  {
    slug: "2018-prizm-luka-doncic-base-psa-9",
    brand: "Panini",
    condition: "graded",
    sku: "ARN-C-0008",
    category: "card",
    name: "2018–19 Prizm #280",
    subject: "Luka Dončić",
    year: 2018,
    sport: "Basketball",
    price: 240000,
    stock: 3,
    tagline: "The modern base rookie everybody actually wants.",
    accent: "#9333EA",
    story: [
      "Prizm base rookies are the entry point to the modern hobby, and Luka's is the one that keeps climbing.",
      "Clean surface, strong corners, well centered for the issue.",
    ],
    spec: {
      set: "2018–19 Panini Prizm Basketball",
      cardNumber: "280",
      grader: "PSA",
      grade: "MINT 9",
      certNumber: "70112884",
      popAtGrade: 12408,
      popHigher: 3170,
    },
    provenance: [
      { year: "2018", title: "Release", detail: "Pulled at release." },
      { year: "2023", title: "Graded", detail: "PSA MINT 9." },
    ],
  },
  {
    slug: "2020-prizm-football-mega-box",
    brand: "Panini",
    sku: "ARN-W-0003",
    category: "wax",
    name: "2020 Prizm Football Mega Box",
    subject: "Sealed Retail Wax",
    year: 2020,
    sport: "Football",
    price: 89000,
    compareAt: 105000,
    stock: 6,
    tagline: "Sealed retail from a class people still chase.",
    accent: "#CA8A04",
    story: [
      "A sealed mega box from one of the most-chased modern football classes. Unsearched, unopened, straight from a sealed pallet.",
      "Factory shrink fully intact.",
    ],
    spec: {
      set: "2020 Panini Prizm Football",
      format: "Mega Box",
      packCount: "10 packs × 4 cards",
      sealType: "Factory shrink wrap",
      grader: "None",
      sealIntegrity: "Intact factory shrink, unsearched",
    },
    provenance: [
      { year: "2020", title: "Retail release", detail: "From a sealed pallet." },
      { year: "2026", title: "Listed by ARENA", detail: "Seal verified on intake." },
    ],
  },
  {
    slug: "2021-topps-chrome-ucl-hobby-box",
    brand: "Topps",
    sku: "ARN-W-0004",
    category: "wax",
    name: "2021–22 Topps Chrome UCL Box",
    subject: "Sealed Hobby Wax",
    year: 2021,
    sport: "Soccer",
    price: 34000,
    stock: 12,
    tagline: "Champions League chrome. Rip it or keep it sealed.",
    accent: "#0EA5E9",
    story: [
      "Topps Chrome UEFA Champions League — the set that pulled a whole generation of football fans into cards.",
      "Sealed hobby box, factory shrink intact.",
    ],
    spec: {
      set: "2021–22 Topps Chrome UCL",
      format: "Hobby Box",
      packCount: "18 packs × 4 cards",
      sealType: "Factory shrink wrap",
      grader: "None",
      sealIntegrity: "Intact factory shrink",
    },
    provenance: [
      { year: "2021", title: "Hobby release", detail: "Direct from hobby distribution." },
    ],
  },
  {
    slug: "signed-mini-helmet-modern-qb",
    sku: "ARN-S-0004",
    category: "signed",
    name: "Signed Mini Helmet",
    subject: "Patrick Mahomes",
    year: 2023,
    sport: "Football",
    price: 68000,
    stock: 4,
    tagline: "Certified on-helmet signature, display ready.",
    accent: "#B91C1C",
    story: [
      "Riddell mini helmet signed on the shell in silver paint pen. Bold placement, clean ink.",
      "Fanatics Authentic hologram and online verification.",
    ],
    spec: {
      item: "Riddell mini helmet",
      inscription: "Signed on shell",
      medium: "Silver paint pen on polycarbonate",
      authenticator: "Fanatics",
      certNumber: "FA-1180294",
      signingContext: "Official Fanatics private signing",
      dimensions: "Mini scale, 15 cm",
    },
    provenance: [
      { year: "2023", title: "Official signing", detail: "Fanatics private signing." },
    ],
  },
  {
    slug: "2019-topps-chrome-acuna-refractor",
    brand: "Topps",
    condition: "graded",
    sku: "ARN-C-0009",
    category: "card",
    name: "2019 Topps Chrome Refractor",
    subject: "Ronald Acuña Jr.",
    year: 2019,
    sport: "Baseball",
    price: 12500,
    stock: 8,
    tagline: "Entry-level refractor with real upside.",
    accent: "#DB2777",
    story: [
      "A clean refractor from a player who keeps rewriting his own ceiling. Raw, sleeved and toploaded.",
    ],
    spec: {
      set: "2019 Topps Chrome Baseball",
      cardNumber: "117",
      grader: "PSA",
      grade: "Raw — ungraded",
      certNumber: "—",
      popAtGrade: 0,
      popHigher: 0,
      surface: "Raw. Inspected; no visible surface damage",
    },
    provenance: [
      { year: "2019", title: "Release", detail: "Pulled at release, sleeved immediately." },
    ],
  },
  {
    slug: "arena-mystery-slab-pack",
    brand: "Other",
    condition: "graded",
    sku: "ARN-X-0001",
    category: "card",
    name: "ARENA Mystery Slab",
    subject: "Mystery Graded Card",
    year: 2026,
    sport: "Basketball",
    price: 8500,
    stock: 24,
    tagline: "One graded slab. Minimum $120 book value. No duds.",
    accent: "#B5FF00",
    hot: true,
    story: [
      "One randomly selected graded card from our overflow, every single one with a book value above the sticker price. We built these because we had too much good mid-tier stock and not enough shelf.",
      "Every slab is PSA, BGS or SGC. No raw cards, no filler, no reprints.",
    ],
    spec: {
      set: "Mixed — 1980s to present",
      cardNumber: "—",
      grader: "PSA",
      grade: "Varies — 8 or better",
      certNumber: "Revealed on despatch",
      popAtGrade: 0,
      popHigher: 0,
      surface: "Every slab inspected before it goes in the box",
    },
    provenance: [
      { year: "2026", title: "Assembled by ARENA", detail: "Pulled from graded overflow stock." },
    ],
  },

  /* ---------------- Supplies ---------------- */
  {
    slug: "arena-penny-sleeves-500",
    sku: "ARN-P-0001",
    category: "supplies",
    name: "Penny Sleeves · 500 ct",
    subject: "Soft Sleeves",
    year: 2026,
    sport: "Basketball",
    price: 900,
    stock: 140,
    tagline: "The first thing that touches the card. Buy more than you need.",
    accent: "#64748B",
    story: [
      "Acid-free, no PVC, and cut generously enough that you are not forcing a corner in. The cheapest insurance in the hobby.",
      "500 per pack. If you are sending to grading, sleeve first, then semi-rigid.",
    ],
    spec: {
      brand: "ARENA",
      contents: "500 sleeves",
      fits: "Standard 2.5 × 3.5 in cards",
      material: "Acid-free polypropylene, PVC-free",
      dimensions: "2.6 × 3.6 in",
    },
    provenance: [{ year: "2026", title: "Stocked", detail: "House-branded, made to our spec." }],
  },
  {
    slug: "arena-toploaders-35pt-100",
    sku: "ARN-P-0002",
    category: "supplies",
    name: "Toploaders 35pt · 100 ct",
    subject: "Rigid Toploaders",
    year: 2026,
    sport: "Basketball",
    price: 2400,
    stock: 86,
    tagline: "Rigid, crystal clear, and actually 35pt.",
    accent: "#0EA5E9",
    story: [
      "Standard 35pt toploaders for sleeved base and rookies. Clear enough to read the back without pulling the card.",
      "Pair with a penny sleeve — never load a raw card straight in.",
    ],
    spec: {
      brand: "ARENA",
      contents: "100 toploaders",
      fits: "Sleeved cards up to 35pt",
      material: "Rigid PVC, archival safe",
      dimensions: "3 × 4 in",
    },
    provenance: [{ year: "2026", title: "Stocked", detail: "House-branded, made to our spec." }],
  },
  {
    slug: "arena-one-touch-magnetic-35pt",
    sku: "ARN-P-0003",
    category: "supplies",
    name: "Magnetic One-Touch 35pt",
    subject: "One-Touch Holder",
    year: 2026,
    sport: "Basketball",
    price: 450,
    compareAt: 600,
    stock: 3,
    tagline: "UV-protected magnetic case. What you display in.",
    accent: "#B5FF00",
    hot: true,
    story: [
      "Magnetic closure, UV-resistant acrylic, and a snug fit that will not rattle. This is the holder for anything you actually want on a shelf.",
      "Sold singly so you can buy exactly as many as you need.",
    ],
    spec: {
      brand: "ARENA",
      contents: "1 holder",
      fits: "Raw cards up to 35pt",
      material: "UV-resistant acrylic, magnetic closure",
      dimensions: "3.4 × 4.4 in",
    },
    provenance: [{ year: "2026", title: "Stocked", detail: "House-branded, made to our spec." }],
  },
  {
    slug: "arena-graded-slab-box",
    sku: "ARN-P-0004",
    category: "supplies",
    name: "Graded Slab Storage Box",
    subject: "Slab Box",
    year: 2026,
    sport: "Basketball",
    price: 3200,
    stock: 42,
    tagline: "Holds 20 slabs. Stacks without bowing.",
    accent: "#A16207",
    story: [
      "Corrugated storage sized for PSA, BGS and SGC holders, with a lid that stays on. Walls thick enough to stack three high without the bottom box giving way.",
    ],
    spec: {
      brand: "ARENA",
      contents: "1 box, holds 20 slabs",
      fits: "PSA, BGS and SGC holders",
      material: "Double-wall corrugate, acid-free",
      dimensions: "14 × 4.5 × 4 in",
    },
    provenance: [{ year: "2026", title: "Stocked", detail: "House-branded, made to our spec." }],
  },
  {
    slug: "arena-submission-starter-kit",
    sku: "ARN-P-0005",
    category: "supplies",
    name: "Grading Submission Kit",
    subject: "Submission Kit",
    year: 2026,
    sport: "Basketball",
    price: 5900,
    stock: 0,
    tagline: "Everything you need to send cards off properly.",
    accent: "#7C3AED",
    story: [
      "Semi-rigids, sleeves, a team bag and a roll of blue painter's tape — the exact kit graders ask for, and the one most first submissions get wrong.",
      "Currently sold out. More on the way.",
    ],
    spec: {
      brand: "ARENA",
      contents: "100 semi-rigids, 200 sleeves, 20 team bags, 1 tape roll",
      fits: "Standard cards for PSA / BGS / SGC submission",
      material: "Acid-free throughout",
    },
    provenance: [{ year: "2026", title: "Stocked", detail: "Assembled in house." }],
  },
];

/* ---------- Access helpers. Keep every lookup here. ---------- */

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function featuredProducts(): Product[] {
  return PRODUCTS.filter((p) => p.featured);
}

export function relatedProducts(product: Product, limit = 4): Product[] {
  const same = PRODUCTS.filter(
    (p) => p.slug !== product.slug && p.category === product.category,
  );
  const rest = PRODUCTS.filter(
    (p) => p.slug !== product.slug && p.category !== product.category,
  );
  return [...same, ...rest].slice(0, limit);
}

export function allSports(): Sport[] {
  return [...new Set(PRODUCTS.map((p) => p.sport))].sort();
}

export function allCategories(): Category[] {
  return CATEGORY_ORDER;
}

export function countByCategory(category: Category): number {
  return PRODUCTS.filter((p) => p.category === category).length;
}
